# Generated by Django 4.1.1 on 2023-02-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='admin123', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
