# Generated by Django 4.1.1 on 2023-02-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='temp_id',
            new_name='id',
        ),
    ]
