# Generated by Django 4.1.1 on 2023-02-05 08:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dvhxqdx5f/image/upload/v1675587286/default_xy0uwu.jpg', max_length=255, null=True),
        ),
    ]
