# Generated by Django 4.1 on 2022-08-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_message_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(max_length=500, verbose_name='Add a Comment'),
        ),
    ]
