# Generated by Django 4.1 on 2022-08-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated_on', '-created_on']},
        ),
    ]
