# Generated by Django 4.1.1 on 2022-11-17 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_topic_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='user',
            new_name='host',
        ),
    ]
