# Generated by Django 4.1.1 on 2022-11-23 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_user_topic_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='host',
        ),
        migrations.AddField(
            model_name='topic',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
